### ISSUE TITLE
Error: error:0308010C:digital envelope routines::unsupported

### ISSUE THREAD

**Issue by perryraskin** [edwilliams/docz-vs-storybook#1]
Any idea here?

```
docz dev

● Docz █████████████████████████ building (10%) 2/3 modules 1 active
 node_modules/docz-core/node_modules/react-dev-utils/webpackHotDevClient.js

node:internal/crypto/hash:68
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:68:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports (/workspace/docz-vs-storybook/node_modules/webpack/lib/util/createHash.js:90:53)
    at NormalModule._initBuildHash (/workspace/docz-vs-storybook/node_modules/webpack/lib/NormalModule.js:401:16)
    at handleParseError (/workspace/docz-vs-storybook/node_modules/webpack/lib/NormalModule.js:449:10)
    at /workspace/docz-vs-storybook/node_modules/webpack/lib/NormalModule.js:481:5
    at /workspace/docz-vs-storybook/node_modules/webpack/lib/NormalModule.js:342:12
    at /workspace/docz-vs-storybook/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/workspace/docz-vs-storybook/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/workspace/docz-vs-storybook/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/workspace/docz-vs-storybook/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:43:16)
    at /workspace/docz-vs-storybook/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:79:9
    at /workspace/docz-vs-storybook/node_modules/graceful-fs/graceful-fs.js:90:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read/context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
```

**Comment by edwilliams** [comment]
> Any idea here?
> 
> 
> 
> ```
> 
> docz dev
> 
> 
> 
> ● Docz █████████████████████████ building (10%) 2/3 modules 1 active
> 
>  node_modules/docz-core/node_modules/react-dev-utils/webpackHotDevClient.js
> 
> 
> 
> node:internal/crypto/hash:68
> 
>   this[kHandle] = new _Hash(algorithm, xofLen);
> 
>                   ^
> 
> 
> 
> Error: error:0308010C:digital envelope routines::unsupported
> 
>     at new Hash (node:internal/crypto/hash:68:19)
> 
>     at Object.createHash (node:crypto:138:10)
> 
>     at module.exports (/workspace/docz-vs-storybook/node_modules/webpack/lib/util/createHash.js:90:53)
> 
>     at NormalModule._initBuildHash (/workspace/docz-vs-storybook/node_modules/webpack/lib/NormalModule.js:401:16)
> 
>     at handleParseError (/workspace/docz-vs-storybook/node_modules/webpack/lib/NormalModule.js:449:10)
> 
>     at /workspace/docz-vs-storybook/node_modules/webpack/lib/NormalModule.js:481:5
> 
>     at /workspace/docz-vs-storybook/node_modules/webpack/lib/NormalModule.js:342:12
> 
>     at /workspace/docz-vs-storybook/node_modules/loader-runner/lib/LoaderRunner.js:373:3
> 
>     at iterateNormalLoaders (/workspace/docz-vs-storybook/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
> 
>     at Array.<anonymous> (/workspace/docz-vs-storybook/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
> 
>     at Storage.finished (/workspace/docz-vs-storybook/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:43:16)
> 
>     at /workspace/docz-vs-storybook/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:79:9
> 
>     at /workspace/docz-vs-storybook/node_modules/graceful-fs/graceful-fs.js:90:16
> 
>     at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read/context:68:3) {
> 
>   opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
> 
>   library: 'digital envelope routines',
> 
>   reason: 'unsupported',
> 
>   code: 'ERR_OSSL_EVP_UNSUPPORTED'
> 
> ```

Think it's a Node version issue. You might have to start it with NODE_OPTIONS=--openssl-legacy-provider
